name: Build and release

on:
  release:
    types:
      - published
  # workflow_dispatch:
  #   inputs:
  #     tags:
  #       description: 'Docker Tags to Deploy or just insert empty for production'
  #       required: true
  #       type: string

jobs:
  # test:
  #   name: Test
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  build-release:
    name: Build and release
    # needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42
      - name: Build and release
        run: |
          bun install --frozen-lockfile
          bun run release